apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: is-syn-segment-in-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '30Gi'
