apiVersion: v1
kind: Service
metadata:
  name: ch-lb
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8123
      protocol: TCP
      targetPort: 8123
    - name: tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    clickhouse.altinity.com/app: chop
    clickhouse.altinity.com/chi: ch-cxs
    clickhouse.altinity.com/namespace: default
    clickhouse.altinity.com/ready: 'yes'