apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "ch-cxs"
spec:
  troubleshoot: "yes"
  defaults:
    templates:
        podTemplate: clickhouse-pod
        serviceTemplate: chi-service-template
  configuration:
    users:
      default/password_sha256_hex: "2b02a9cfa819b25e5e08c19c86ab89c58da3a958b003bed64f118160872a7bf3"
    files:
      config.d/storage_config.xml: |-
        <clickhouse>
          <storage_configuration>
            <disks>
              <s3>
                <type>s3</type>
                <endpoint>https://chs3data.s3.eu-west-1.amazonaws.com/ctx-s3/</endpoint>
                <region>eu-west-1</region>
                <access_key_id from_env="AWS_ACCESS_KEY_ID"/>
                <secret_access_key from_env="AWS_SECRET_ACCESS_KEY"/>
                <metadata_path>/var/lib/clickhouse/disks/s3-metadata/</metadata_path>
              </s3>        
              <cache>
                  <type>cache</type>
                  <disk>s3</disk>
                  <path>/var/lib/clickhouse/disks/s3-cache/</path>
                  <max_size>300Gi</max_size>
              </cache>        
            </disks>
            <policies>
              <s3tiered>
                  <volumes>
                      <default>
                          <disk>default</disk>
                          <max_data_part_size_bytes>50000000000</max_data_part_size_bytes>         
                      </default>
                      <s3cached>
                          <disk>cache</disk>                          
                      </s3cached>
                  </volumes>
              </s3tiered>
            </policies>        
          </storage_configuration>        
        </clickhouse>
    clusters:
      - name: cxss3
        layout:
          shardsCount: 1
          replicasCount: 3
    zookeeper:
      nodes:
        - host: zookeeper
          port: 2181
      session_timeout_ms: 30000
      operation_timeout_ms: 10000
      root: "/cxss3"
  templates:
    podTemplates:
      - name: clickhouse-pod
        generateName: "{chi}-{cluster}-{host}"
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: "clickhouse.altinity.com/app"
                        operator: In
                        values:
                          - "chop"
                  topologyKey: "kubernetes.io/hostname"
          volumes:
            - name: local-path
              hostPath:
                path: /data/clickhouse/persistence/cxss3
                type: DirectoryOrCreate
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:23.10.5
              volumeMounts:
                - mountPath: /var/lib/clickhouse
                  name: local-path
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: clickhouse
                      key: access_key_id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: clickhouse
                      key: secret_access_key
    serviceTemplates:
      - name: chi-service-template
        generateName: "{chi}-lb"
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: LoadBalancer
          loadBalancerIP: 192.168.50.68
          externalTrafficPolicy: Cluster