apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse"
spec:
  troubleshoot: "yes"
  defaults:
    - templates:
        podTemplate: clickhouse-pod-A
  configuration:
    files:
      config.d/storage_config.xml: |-
        <clickhouse>
          <storage_configuration>
            <disks>
              <s3>
                <type>s3</type>
                <endpoint>https://cxs-ch-backup.s3.eu-west-1.amazonaws.com/chs3/</endpoint>
                <access_key_id>AKIASUTW6HDONHUV32NI</access_key_id>
                <secret_access_key>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</secret_access_key>
                <region>eu-west-1</region>
                <metadata_path>/var/lib/clickhouse/disks/s3/</metadata_path>
              </s3>
              <s3_cache>
                <type>cache</type>
                <disk>s3</disk>
                <path>/var/lib/clickhouse/disks/s3_cache/</path>
                <max_size>300Gi</max_size>
              </s3_cache>
            </disks>
            <policies>
                <s3_main>
                    <volumes>
                        <main>
                            <disk>s3</disk>
                        </main>
                    </volumes>
                </s3_main>
            </policies>        
          </storage_configuration>        
        </clickhouse>
    clusters:
      - name: chs3
        layout:
          shardsCount: 1
          replicasCount: 3
          replicas:
            - templates:
                podTemplate: clickhouse-pod-A
            - templates:
                podTemplate: clickhouse-pod-B

    zookeeper:
      nodes:
        - host: zookeeper
          port: 2181
      session_timeout_ms: 30000
      operation_timeout_ms: 10000
      root: "/chs3"
  templates:
    podTemplates:
      - name: clickhouse-pod-A
        generateName: "{chi}-{cluster}-{host}"
        spec:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: "clickhouse.altinity.com/app"
                      operator: In
                      values:
                        - "chop"
                topologyKey: "kubernetes.io/hostname"
          volumes:
            - name: local-path
              hostPath:
                path: /data/clickhouse/persistence
                type: DirectoryOrCreate
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:23.10.5
              volumeMounts:
                - mountPath: /var/lib/clickhouse
                  name: local-path
      - name: clickhouse-pod-B
        generateName: "{chi}-{cluster}-{host}"
        spec:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: "clickhouse.altinity.com/app"
                      operator: In
                      values:
                        - "chop"
                topologyKey: "kubernetes.io/hostname"
          volumes:
            - name: local-path
              hostPath:
                path: /data/clickhouse/persistence
                type: DirectoryOrCreate
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:23.10.5
              volumeMounts:
                - mountPath: /var/lib/clickhouse
                  name: local-path
