apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse"
spec:
  troubleshoot: "yes"
  defaults:
  configuration:
    clusters:
      - name: chs3
        layout:
          shardsCount: 1
          replicasCount: 1
        templates:
          podTemplate: clickhouse-pod
    zookeeper:
      nodes:
        - host: zookeeper
          port: 2181
      session_timeout_ms: 30000
      operation_timeout_ms: 10000
      root: "/chs3"
  templates:
    podTemplates:
      - name: clickhouse-pod
        generateName: "{chi}-{cluster}-{host}"
        spec:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: "clickhouse.altinity.com/app"
                        operator: In
                        values:
                          - "chop"
                  topologyKey: "kubernetes.io/hostname"
            volumes:
              - name: local
                hostPath:
                path: /data/clickhouse/persistence
            containers:
              - name: clickhouse-pod
                image: clickhouse/clickhouse-server:23.11
                volumeMounts:
                  - mountPath: /var/lib/clickhouse
                    name: local
