apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "ch"
spec:
  troubleshoot: "yes"
  defaults:
    templates:
        podTemplate: clickhouse-pod
  configuration:
    users:
      default/password_sha256_hex: "2b02a9cfa819b25e5e08c19c86ab89c58da3a958b003bed64f118160872a7bf3"
    clusters:
      - name: ctx-s3
        layout:
          shardsCount: 1
          replicasCount: 1
          replicas:
            - templates:
                podTemplate: clickhouse-pod
    zookeeper:
      nodes:
        - host: zookeeper
          port: 2181
      session_timeout_ms: 30000
      operation_timeout_ms: 10000
      root: "/chs3"
  templates:
    podTemplates:
      - name: clickhouse-pod
        generateName: "{chi}-{cluster}-{host}"
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: "clickhouse.altinity.com/app"
                    operator: In
                    values:
                    - "chop"
                topologyKey: "topology.kubernetes.io/zone"
          volumes:
            - name: local-path
              hostPath:
                path: /data/clickhouse/persistence
                type: DirectoryOrCreate
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: clickhouse
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: clickhouse
                  key: secret_access_key
          containers:
            - name: clickhouse-pod
              image: clickhouse/clickhouse-server:23.10.5
              volumeMounts:
                - mountPath: /var/lib/clickhouse
                  name: local-path