apiVersion: v1
kind: ConfigMap
metadata:
  name: ctx-config
  # NO SECRETS SHOULD BE STORED IN CONFIGMAPS [See the docs](/README.md))
data:
  OPENAI_LLM: 'Azure'
  KAFKA_HOST: localhost
  KAFKA_PORT: 9092
  KAFKA_TOPIC: ctx
  KAFKA_TEST_TOPIC: ctx_test

  ## Redis
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  REDIS_DB: 0
  REDIS_PASSWORD: ''

