apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctxllm
spec:
  selector:
    matchLabels:
      app: ctxllm
      tier: api
  template:
    metadata:
      labels:
        app: ctxllm
        tier: api
    spec:
      containers:
        - name: node
          image: quicklookup/ctxllm:29ca5cf
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - mountPath: /cdn
              name: cdn
          ports:
            - containerPort: 4001
          livenessProbe:
            httpGet:
              port: 4001
              path: /api/status/alive
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 4001
              path: /api/status/ready
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-postgresql-ha-pgpool
                key: password
          - name: NEO4J_PASSWORD
            valueFrom:
              secretKeyRef:
                name: contextsuite
                key: NEO4J_AUTH
          - name: CLICKHOUSE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: clickhouse
                key: admin-password
          - name: SOLR_PASSWORD
            valueFrom:
              secretKeyRef:
                name: solr
                key: solr-password
          envFrom:
            - configMapRef:
                name: ctxllm-config
      imagePullSecrets:
        - name: dockerlock
      volumes:
        - name: cdn
          hostPath:
            path: /data/cdn

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ctxllm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ctxllm
  maxReplicas: 4
  minReplicas: 2
  targetCPUUtilizationPercentage: 60