apiVersion: v1
kind: Service
metadata:
  name: cxss3
  labels:
    app: cxss3
    tier: persistence
spec:
  type: ClusterIP
  ports:
    - port: 9000
    - port: 8123
  selector:
    app: cxss3
    tier: persistence
