# Setup ClickHouse Keeper settings
apiVersion: v1
kind: ConfigMap
metadata:
  name: cxss3-config
data:
  storage_config.xml: |-
    <clickhouse>
        <storage_configuration>
            <disks>
                <default>
                    <keep_free_space_bytes>0</keep_free_space_bytes>
                </default>
                <data>
                    <path>/data/</path>
                    <keep_free_space_bytes>0</keep_free_space_bytes>
                </data>
                <s3>
                    <type>s3</type>
                    <endpoint>https://chs3data.s3.eu-west-1.amazonaws.com/cxss3-s3/</endpoint>
                    <!--endpoint>https://s3.eu-west-1.amazonaws.com/cxss3-s3/</endpoint-->
                    <access_key_id from_env="AWS_ACCESS_KEY_ID"/>
                    <secret_access_key from_env="AWS_SECRET_ACCESS_KEY"/>
                </s3>
                <s3_cache>
                    <type>cache</type>
                    <disk>s3</disk>
                    <path>/var/lib/clickhouse/disks/s3-cache/</path>
                    <max_size>300Gi</max_size>
                </s3_cache>
                <backups>
                    <type>local</type>
                    <path>/backups/</path>
                </backups>                
            </disks>
            <backups>
                <allowed_disk>backups</allowed_disk>
                <allowed_path>/backups/</allowed_path>
            </backups>
            <policies>
                <local>
                    <volumes>
                        <main>
                            <disk>data</disk>
                        </main>
                    </volumes>
                </local>
                <s3_tiered>
                    <volumes>
                        <hot>
                            <disk>data</disk>
                        </hot>
                        <main>
                            <disk>s3</disk>
                        </main>
                    </volumes>
                    <move_factor>0.2</move_factor>
                </s3_tiered>                
                <s3_main>
                    <volumes>
                        <main>
                            <disk>s3_cache</disk>
                        </main>
                    </volumes>
                </s3_main>
            </policies>
        </storage_configuration>        
    </clickhouse>
  config.xml: |-
    <clickhouse>
        <logger>
            <level>information</level>
            <console>true</console>
            <!--log remove="remove"/-->
            <!--errorlog remove="remove"/-->
            <console>1</console>
        </logger>
        <query_log>
            <database>system</database>
            <table>query_log</table>
        </query_log>
        <listen_host>0.0.0.0</listen_host>
        <http_port>8123</http_port>
        <tcp_port>9000</tcp_port>
        <interserver_http_port>9009</interserver_http_port>
        <!--interserver_http_host>cxss3.contextsuite.com</interserver_http_host-->
        <users>
            <default>
                <password_sha256_hex>2b02a9cfa819b25e5e08c19c86ab89c58da3a958b003bed64f118160872a7bf3</password_sha256_hex>
            </default>
        </users>
        <user_directories>
            <users_xml>
                <path>users.xml</path>
            </users_xml>
            <local_directory>
                <path>/var/lib/clickhouse/access/</path>
            </local_directory>
        </user_directories>
        <distributed_ddl>
            <path>/clickhouse/task_queue/ddl</path>
        </distributed_ddl>
        <macros>
            <cluster>default</cluster>
            <shard>1</shard>
            <replica from_env="HOSTNAME"/>
        </macros>        
        <default_replica_path>/clickhouse/tables/{shard}/{database}/{table}</default_replica_path>
        <default_replica_name>{replica}</default_replica_name>
        <remote_servers>
            <default>
                <shard>
                    <internal_replication>true</internal_replication>
                    <replica>
                        <host>cxss3-0</host>
                        <port>9000</port>
                    </replica>
                    <replica>
                        <host>cxss3-1</host>
                        <port>9000</port>
                    </replica>
                    <replica>
                        <host>cxss3-2</host>
                        <port>9000</port>
                    </replica>
                    <!--replica>
                        <host>cxss3-3</host>
                        <port>9000</port>
                    </replica-->
                </shard>
            </default>
        </remote_servers>
        <zookeeper>
            <node>
                <host>keeper-0.keeper.default.svc.cluster.local</host>
                <port>9181</port>
            </node>
            <node>
                <host>keeper-1.keeper.default.svc.cluster.local</host>
                <port>9181</port>
            </node>
            <node>
                <host>keeper-2.keeper.default.svc.cluster.local</host>
                <port>9181</port>
            </node>
        </zookeeper>
    </clickhouse>
      
