apiVersion: v1
kind: Pod
metadata:
  name: islandshotel2kafka
spec:
  containers:
  - name: islandshotel2kafka
    image: quicklookup/ohip-shovel:139f60a
    env:
      - name: APIGW_URL
        value: https://mtce4pr.hospitality-api.eu-frankfurt-1.ocs.oraclecloud.com
      - name: WS_URL
        value: wss://mtce4pr.hospitality-api.eu-frankfurt-1.ocs.oraclecloud.com
      - name: OAUTH_ENDPOINT
        value: /oauth/v1/tokens
      - name: SUBS_ENDPOINT
        value: /subscriptions
      - name: APP_KEY
        valueFrom:
          secretKeyRef:
            name: islandshotel
            key: APP_KEY
      - name: INTEGRATION_USER
        valueFrom:
          secretKeyRef:
            name: islandshotel
            key: INTEGRATION_USER
      - name: INTEGRATION_PASSWORD
        valueFrom:
          secretKeyRef:
            name: islandshotel
            key: INTEGRATION_PASSWORD
      - name: CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: islandshotel
            key: CLIENT_ID
      - name: CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: islandshotel
            key: CLIENT_SECRET
      - name: TOKEN_EXPIRY
        value: "3540000"
      - name: PING
        value: "20000"
      - name: TIMER
        value: "10000"
      - name: CHAIN
        value: ISLHTL
      - name: DELTA
        value: "true"
      - name: LOGLEVEL
        value: "debug"
      - name: STATS
        value: "false"
      - name: TIME_BUCKET
        value: "HOUR"
      - name: RUN_FOR
        value: "0"
      - name: DUMP_TO_FILE
        value: "false"
      - name: KAFKA_HOST
        value: "kafka-broker-0.kafka-broker-headless.data.svc.cluster.local:9092"
      - name: KAFKA_USER
        valueFrom:
          secretKeyRef:
            name: islandshotel
            key: KAFKA_USER
      - name: KAFKA_PASSWORD
        valueFrom:
          secretKeyRef:
            name: islandshotel
            key: KAFKA_PASSWORD
      - name: KAFKA_TOPIC
        value: "se2-islandshotel-is"
      - name: KAFKA_ENABLED
        value: "true"
      - name: GRAPHQL_CLIENT_ID
        value: "34dc670d-0160-4a69-8fcc-f77643754445"
  dnsPolicy: ClusterFirst
  imagePullSecrets:
    - name: dockerlock


