apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctxpipe
spec:
  selector:
    matchLabels:
      app: ctxpipe
      tier: api
  replicas: 3
  template:
    metadata:
      labels:
        app: ctxpipe
        tier: api
    spec:
      containers:
      - name: ctxpipe
        image: quicklookup/ctxpipe:247827b
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - name: pipedrive
            mountPath: /process
          - name: pipedb
            mountPath: /pipedb
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-postgresql-ha-pgpool
                key: password
          - name: CLICKHOUSE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: clickhouse
                key: admin-password
        envFrom:
          - configMapRef:
              name: ctxpipe-config

      imagePullSecrets:
        - name: dockerlock
      volumes:
        - name: pipedrive
        - name: pipedb
          hostPath:
            path: /data/ctxpipe

---
volumeClaimTemplates:
- metadata:
    name: pipedrive
  spec:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "longhorn"
    resources:
      requests:
        storage: 20Gi

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ctxpipe
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ctxpipe
  maxReplicas: 1
  minReplicas: 1
  targetCPUUtilizationPercentage: 60