apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctxpipe
spec:
  selector:
    matchLabels:
      app: ctxpipe
      tier: api
  replicas: 3
  template:
    metadata:
      labels:
        app: ctxpipe
        tier: api
    spec:
      containers:
      - name: ctxpipe
        image: quicklookup/ctxpipe:247827b
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - mountPath: /data
            name: pipedrive
        ports:
        - containerPort: 8088
        livenessProbe:
          httpGet:
            port: 8088
            path: /api/status/alive
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            port: 8088
            path: /api/status/ready
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-postgresql-ha-pgpool
                key: password
          - name: CLICKHOUSE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: clickhouse
                key: admin-password
        envFrom:
          - configMapRef:
              name: ctxpipe-config

      imagePullSecrets:
        - name: dockerlock
      volumes:
        - name: pipedrive
          hostPath:
            path: /data/ctxpipe

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ctxpipe
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ctxpipe
  maxReplicas: 1
  minReplicas: 1
  targetCPUUtilizationPercentage: 60