apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    field.cattle.io/description: stores semantic events Sýn
  labels:
    job-name: nova2ch-pipeline
  name: nova2ch-pipeline
spec:
  selector:
    matchLabels:
      job-name: nova2ch-pipeline
  template:
    metadata:
      labels:
        job-name: nova2ch-pipeline
    spec:
      containers:
        - env:
          - name: TIMEOUT
            value: '60'
          - name: KAFKA_BATCH_SIZE
            value: '5000'
          - name: BATCH_SIZE
            value: '10000'
          - name: SNAPSHOT_INTERVAL
            value: '8640'
          - name: TABLE
            value: 'semantic.sem_events'
          - name: WRITE_KEY
            value: ''
          - name: RECOVERY_DIR
            value: '/pipedrive/syn2ch'
          - name: RECOVERY_INIT
            value: 'python -m bytewax.recovery /pipedrive/nova2ch/ 2'
          - name: DB_PATH
            value: '/pipedrive/databases'
          - name: CLICKHOUSE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: admin-password
                name: clickhouse
                optional: false
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: postgresql-postgresql-ha-pgpool
                optional: false
          envFrom:
            - configMapRef:
                name: ctxpipe-config
          image: quicklookup/ctxpipe:9616a9b
          imagePullPolicy: IfNotPresent
          name: pipe-adventures-0
          volumeMounts:
            - mountPath: /pipedrive
              name: pipedrive
      imagePullSecrets:
        - name: dockerlock
      restartPolicy: Never
      volumes:
        - hostPath:
            path: /data/pipedrive
          name: pipedrive
