apiVersion: v1
kind: Job
metadata:
  name: nova2ch
spec:
  containers:
  - name: nova2ch
    image: quicklookup/qlingress:1.0.6
    env:
      - name: CLICKHOUSE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: clickhouse
            key: admin-password
    envFrom:
      - configMapRef:
          name: ctxpipe-config
    volumeMounts:
      - name: pipedrive
        mountPath: /pipedrive
    securityContext:
      readOnlyRootFilesystem: false
      runAsUser: 0
      capabilities:
        add:
          - NET_ADMIN
  dnsPolicy: ClusterFirst
  volumes:
    - name: pipedrive
      hostPath:
        path: /data/pipedrive
  imagePullSecrets:
    - name: dockerlock
