apiVersion: v1
kind: ConfigMap
metadata:
  name: ctxin-config
data:
  ## Kafka
  KAFKA_BOOTSTRAP_SERVERS: 'kafka.default'
  KAFKA_PORT: '9092'

  ## Redis
  REDIS_HOST: 'redis-master.default'
  REDIS_PORT: '6379'
  REDIS_DB: '0'
  REDIS_LOCAL: 'true'

  ## Postgres
  POSTGRES_HOST: 'postgresql-postgresql-ha-pgpool.default'
  POSTGRES_PORT: '5432'
  POSTGRES_DB: 'ssp'
  POSTGRES_USER: 'postgres'
