apiVersion: apps/v1
kind: Deployment
metadata:
  name: gptapi
spec:
  selector:
    matchLabels:
      app: gptapi
      tier: api
  template:
    metadata:
      labels:
        app: gptapi
        tier: api
    spec:
      containers:
        - name: node
          image: quicklookup/gptapi:1.0.4
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: /api/status/alive
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8000
              path: /api/status/ready
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: gptapi-secret
                key: OPENAI_API_KEY
          - name: FRESHDESK_API_KEY
            valueFrom:
              secretKeyRef:
                name: gptapi-secret
                key: FRESHDESK_API_KEY
          envFrom:
            - configMapRef:
                name: gpt-config
      imagePullSecrets:
        - name: dockerlock
      volumes:
        - name: tmp


---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gptapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gptapi
  maxReplicas: 4
  minReplicas: 2
  targetCPUUtilizationPercentage: 60