apiVersion: v1
kind: ConfigMap
metadata:
  name: gpt-api-config
  # NO SECRETS SHOULD BE STORED IN CONFIGMAPS [See the docs](/README.md))
data:
  DEFAULT_LLM_MODEL: "Azure"
  OPENAI_LLM_STREAM_ANSWER: "gpt_4"
  OPENAI_LLM_MAKE_DREAM_TOUR: "gpt_3_5_turbo"
  OPENAI_LLM_SUMMARISER: "gpt_3_5_turbo"
  SUMMARISATION_WINDOW_N_TOKENS: "2000"
  AZURE_OPENAI_API_TYPE: "azure"
  AZURE_OPENAI_API_VERSION: "2023-05-15"
  AZURE_OPENAI_API_BASE_gpt_3_5_turbo: "https://smartdatagpt4.openai.azure.com/"
  AZURE_DEPLOYMENT_NAME_gpt_3_5_turbo: "GTP-Thor35"
  AZURE_OPENAI_API_BASE_gpt_4: "https://smartdatagpt4.openai.azure.com/"
  AZURE_DEPLOYMENT_NAME_gpt_4: "GPT-Thor"
  ENV: "prod"