apiVersion: v1
kind: Service
metadata:
  name: contextapi
  labels:
    app: contextsuite
    tier: api
spec:
  type: NodePort
  ports:
    - port: 4001
  selector:
    app: contextsuite
    tier: api
