apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: is-syn-seg-in-pvc
  namespace: ingress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '20Gi'
  storageClassName: longhorn
  volumeMode: Filesystem
