apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: is-syn-segment-in
  name: is-syn-segment-in
  namespace: solutions
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  suspend: false
  template:
    metadata:
      labels:
        job-name: is-syn-segment-in
      namespace: ingress
    spec:
      containers:
        - image: quicklookup/ctxpipe:f4a410a
          imagePullPolicy: Always
          name: is-syn-segment-in
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: $RECOVERY_DIR
              value: /pipedrive/syn.is.status
            - name: $RECOVERY_INIT
              value: python -m bytewax.recovery /pipedrive/syn.is.status 4
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-postgresql-ha-pgpool
                  key: password
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse
                  key: admin-password
          volumeMounts:
            - mountPath: /pipedrive
              name: is-syn-segment-in-pvc
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: dockerlock
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - name: is-syn-segment-in-pvc
          persistentVolumeClaim:
            claimName: is-syn-segment-in-pvc
