apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsu-config
  # NO SECRETS SHOULD BE STORED IN CONFIGMAPS [See the docs](/README.md))
data:
  ROTOR_URL: "http://10.43.227.186:3401"
  BULKER_URL: "http://10.43.25.123:3042"
  GLOBAL_HASH_SECRET: "dea42a58-acf4-45af-85bb-e77e94bd5025"
  BULKER_AUTH_KEY: "${BULKER_PASSWORD:-4ba41958f341469993fd8ea1c0c932f0}"
  REDIS_URL: "redis://redis-master.default:6379"
  TEST_CREDENTIALS_SHOW_LOGIN: "true"
  NEXTAUTH_URL: "http://jitsu.contextsuite.ai/"
  UPDATE_DB: "true"
  # BULKER_KAFKA_BOOTSTRAP_SERVERS: "kafka.default:9092"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.default:9092"
  KAFKA_MAX_MINUTES_IN_QUEUE: "600"
  BULKER_AUTH_TOKENS: "dea42a58-acf4-45af-85bb-e77e94bd5025"

  # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md