apiVersion: v1
kind: ConfigMap
metadata:
  name: contextapi-config
  # NO SECRETS SHOULD BE STORED IN CONFIGMAPS [See the docs](/README.md))
data:
  ZONE: 'dev_sbx'

  # Redis
  REDIS_URL: 'redis-master.default'
  LOCAL_REDIS: 'true'

  # Postgres
  LIST_DB_NAME: 'list_db'
  DB_CLIENT: 'pg'
  DB_HOST: 'postgresql-postgresql-ha-pgpool.default'
  # DB_HOST: '192.168.50.125'
  DB_USER: 'postgres'
  DB_PORT: '5432'
  DB_NAME: 'ssp'
  DB_SSL: 'false'

  # Neo4j
  NEO4J_USER: 'admin'
  NEO4J_URI: 'neo4j://neo4j.default:7687'
  NEO4J_DATABASE: 'contextsuite'

  # Solr
  SOLR_PORT: '8983'
  SOLR_PATH: '/solr/quicklookup'
  SOLR_CORE: 'quicklookup'
  SOLR_COLLECTION: 'quicklookup'
  SOLR_HOST: 'solr.default.svc.cluster.local'
  SOLR_PROTOCALL: 'http'

  # Clickhouse
  CLICKHOUSE_CONNECTION: 'http://clickhouse.default:8123'
  CLICKHOUSE_USER: 'default'

  GRAPHQL_SERVER_PORT: '4001'
  GRAPHQL_SERVER_PATH: '/context'
  WKT_FOLDER: '/cdn/wkt_cache'

  # NEXT_PUBLIC_GRAPH_API_KEY

  # Sentry
  SENTRY_ENVIRONMENT: 'contextsuite-prod'
  NEXT_PUBLIC_SENTRY_DSN: 'https://97964f08ea76422f830fba0618967fc4@o982223.ingest.sentry.io/5937160'
  SENTRY_DSN: 'https://97964f08ea76422f830fba0618967fc4@o982223.ingest.sentry.io/5937160'
