apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-api
spec:
  selector:
    matchLabels:
      app: gpt-api
      tier: api
  template:
    metadata:
      labels:
        app: gpt-api
        tier: api
    spec:
      containers:
        - name: node
          image: quicklookup/gpt-api:274fcbc
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
          - name: ephemerala
            mountPath: /usr/local/share/fonts
          - name: ephemeralb
            mountPath: /cache
          ports:
            - containerPort: 8000
          env:
            - name: AZURE_OPENAI_API_KEY_gpt-3.5-turbo
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: AZURE_OPENAI_API_KEY_gpt-3.5-turbo
            - name: AZURE_OPENAI_API_KEY_gpt-4
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: AZURE_OPENAI_API_KEY_gpt-4
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: OPENAI_API_KEY
            - name: FRESHDESK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: FRESHDESK_API_KEY
          envFrom:
            - configMapRef:
                name: gpt-api-config
      imagePullSecrets:
        - name: dockerlock
      volumes:
        - name: ephemerala
          emptyDir:
            sizeLimit: 5Gi
        - name: ephemeralb
          emptyDir:
            sizeLimit: 5Gi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gpt-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gpt-api
  maxReplicas: 1
  minReplicas: 1
  targetCPUUtilizationPercentage: 60