apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-api
spec:
  selector:
    matchLabels:
      app: gpt-api
      tier: api
  template:
    metadata:
      labels:
        app: gpt-api
        tier: api
    spec:
      containers:
        - name: node
          image: quicklookup/gpt-api:20d1bca
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
          - name: ephemerala
            mountPath: /usr/local/share/fonts
          - name: ephemeralb
            mountPath: /cache
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: /api/status/alive
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8000
              path: /api/status/ready
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
          env:
            - name: AZURE_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: AZURE_OPENAI_API_KEY_gpt_3_5_turbo
            - name: AZURE_OPENAI_API_KEY_gpt_4
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: AZURE_OPENAI_API_KEY_gpt_4
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: OPENAI_API_KEY
            - name: FRESHDESK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: FRESHDESK_API_KEY
            - name: CHAT_FRESHDESK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: CHAT_FRESHDESK_API_KEY
            - name: BOKUN_PROD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: BOKUN_PROD_API_KEY
            - name: FRESHCHAT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: FRESHCHAT_API_TOKEN
            - name: EVENTS_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: EVENTS_SERVER_KEY
            - name: GOOGLE_MAPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm
                  key: GOOGLE_MAPS_API_KEY
          envFrom:
            - configMapRef:
                name: gpt-api-config
      imagePullSecrets:
        - name: dockerlock
      volumes:
        - name: ephemerala
          emptyDir:
            sizeLimit: 5Gi
        - name: ephemeralb
          emptyDir:
            sizeLimit: 5Gi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gpt-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gpt-api
  maxReplicas: 1
  minReplicas: 1
  targetCPUUtilizationPercentage: 60