apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-api
spec:
  selector:
    matchLabels:
      app: gpt-api
      tier: api
  template:
    metadata:
      labels:
        app: gpt-api
        tier: api
    spec:
      containers:
        - name: node
          image: quicklookup/gpt-api:1789294
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: /api/status/alive
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8000
              path: /api/status/ready
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
          env:
          - name: AZURE_OPENAI_API_KEY_gpt-3.5-turbo
            valueFrom:
              secretKeyRef:
                name: llm
                key: AZURE_OPENAI_API_KEY_gpt-3.5-turbo
          - name: AZURE_OPENAI_API_KEY_gpt-4
            valueFrom:
              secretKeyRef:
                name: llm
                key: AZURE_OPENAI_API_KEY_gpt-4
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: llm
                key: OPENAI_API_KEY
          - name: FRESHDESK_API_KEY
            valueFrom:
              secretKeyRef:
                name: llm
                key: FRESHDESK_API_KEY
          envFrom:
            - configMapRef:
                name: gpt-api-config
          volumeMounts:
            - mountPath: /cache
              name: cache
      imagePullSecrets:
        - name: dockerlock
      volumes:
        - name: cache
          hostPath:
            path: /data/cache

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gpt-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gpt-api
  maxReplicas: 1
  minReplicas: 1
  targetCPUUtilizationPercentage: 60