apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctxin
spec:
  selector:
    matchLabels:
      app: ctxin
      tier: api
  template:
    metadata:
      labels:
        app: ctxin
        tier: api
    spec:
      containers:
        - name: node
          image: quicklookup/ctxin:a16bcbe
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 8088
          livenessProbe:
            httpGet:
              port: 8088
              path: /api/status/alive
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8088
              path: /api/status/ready
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          envFrom:
            - configMapRef:
                name: ctxin-config
      imagePullSecrets:
        - name: dockerlock
