apiVersion: v1
kind: Service
metadata:
  name: ctxin
  labels:
    app: ctxin
    tier: api
spec:
  type: NodePort
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
      name: http
  selector:
    app: ctxin
    tier: api
