apiVersion: v1
kind: Service
metadata:
  labels:
    service: n8n
  name: ingress
  namespace: n8n
spec:
  type: LoadBalancer
  ports:
    - name: "5678"
      port: 5678
      targetPort: 5678
      protocol: TCP
    - name: "http"
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: n8n