apiVersion: v1
kind: Pod
metadata:
  name: aa2ch
spec:
  containers:
  - name: aa2ch
    image: quicklookup/ctxpipe:ab4bc41
    envFrom:
      - configMapRef:
          name: adventures2ch-config
    env:
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgresql-postgresql-ha-pgpool
            key: password
      - name: CLICKHOUSE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: clickhouse
            key: nexus-password
    volumeMounts:
      - mountPath: /pipedrive
        name: pipedrive
      - mountPath: /pipelines/bytewax.run.sh
        name: config-volume
        subPath: bytewax.run.sh

  volumes:
  - name: config-volume
    configMap:
      name: adventures2ch-config
      defaultMode: 0555
  - hostPath:
      path: /data/pipedrive
    name: pipedrive
  imagePullSecrets:
    - name: dockerlock
