apiVersion: v1
kind: ConfigMap
metadata:
  name: adventures2ch-config
data:
  TABLE: 'cst.semantic_events_new'
  WRITE_KEY: 'bZB6!E2d4bz4s8ty'
  RECOVERY_DIR: '/pipedrive/aa2ch'
  RECOVERY_INIT: 'python -m bytewax.recovery /pipedrive/aa2ch/ 2'



  bytewax.run.sh: |
    #!/bin/sh
    python -m bytewax.run -p1 'pipelines/flows/json_kafka_ingress:get_flow("bZB6!E2d4bz4s8ty", batch_size=1000, kafka_batch_size=1000, kafka_topics=["se2-adventures-is"], timeout=10, table="cst.semantic_events_new", from_date="2024-01-15T17:16")'  

  CLICKHOUSE_HOST: 'cxss3.default'
  CLICKHOUSE_PORT: '8123'
  CLICKHOUSE_DB: 'cst'
  CLICKHOUSE_USER: 'cxs'

  KAFKA_HOST: 'kafka.default'
  KAFKA_PORT: '9092'

  REDIS_HOST: 'redis-master.default'
  REDIS_PORT: '6379'
  REDIS_DB: '0'
  REDIS_LOCAL: 'true'

  POSTGRES_PORT: '5432'
  POSTGRES_DB: 'ssp'
  POSTGRES_USER: 'postgres'
  POSTGRES_HOST: 'postgresql-postgresql-ha-postgresql-headless.default'

  DB_PATH: '/pipedrive/databases'
  RAW_PATH: '/pipedrive/raw'
  KEEP_CONTAINER_ALIVE: "false"