apiVersion: v1
kind: Pod
metadata:
  name: aa2ch
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "pipelines"
                operator: In
                values:
                  - "true"
  containers:
  - name: aa2ch
    image: quicklookup/ctxpipe:dbe41b8
    envFrom:
      - configMapRef:
          name: adventures2ch-config
    env:
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgresql-postgresql-ha-pgpool
            key: password
      - name: CLICKHOUSE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: clickhouse
            key: cxss3-password
    volumeMounts:
      - mountPath: /pipedrive
        name: pipedrive
      - mountPath: /pipelines/bytewax.run.sh
        name: config-volume
        subPath: bytewax.run.sh
    imagePullPolicy: Always
    restartPolicy: Always
  volumes:
  - name: config-volume
    configMap:
      name: adventures2ch-config
      defaultMode: 0555
  - hostPath:
      path: /data/pipedrive
    name: pipedrive
  imagePullSecrets:
    - name: dockerlock
