apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qlingress-cdn-rwo-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
