apiVersion: v1
kind: Service
metadata:
  name: jitsu-bulker
  labels:
    app: jitsu-bulker
    tier: ingress
spec:
  type: ClusterIP
  ports:
    - port: 3042
  selector:
    app: jitsu-bulker
    tier: ingress
