apiVersion: v1
kind: Service
metadata:
  name: jitsu-rotor
  labels:
    app: jitsu-rotor
    tier: ingress
spec:
  type: ClusterIP
  ports:
    - port: 3401
  selector:
    app: jitsu-rotor
    tier: ingress
