apiVersion: v1
kind: Service
metadata:
  name: ctxpipe
  labels:
    app: ctxpipe
    tier: etl
spec:
  type: ClusterIP
  ports:
    - port: 9999
    - port: 3030
  selector:
    app: ctxpipe
    tier: etl

