apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipelines-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  volumeName: pipedata
  storageClassName: longhorn-static
  volumeMode: Filesystem