apiVersion: v1
kind: Service
metadata:
  name: pipelines
  labels:
    app: pipelines
    tier: ingress
spec:
  type: ClusterIP
  ports:
    - port: 8088
  selector:
    app: pipelines
    tier: ingress
