# Setup ClickHouse Keeper settings
apiVersion: v1
kind: ConfigMap
metadata:
  name: keeper-config
data:
  keeper_config.xml: |
    <clickhouse>
      <logger>
          <level>warn</level>
          <log>/var/lib/clickhouse/logs/clickhouse-keeper.log</log>
          <errorlog>/var/lib/clickhouse/logs/clickhouse-keeper.err.log</errorlog>
          <size>1000M</size>
          <count>10</count>
      </logger>        
      <listen_host>::1</listen_host>
      <path>/var/lib/clickhouse/</path>
      <core_path>/var/lib/clickhouse/cores</core_path>        
      <keeper_server>
        <tcp_port>2181</tcp_port>
        <server_id>${SERVER_ID}</server_id>
        <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
        <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>    
        <coordination_settings>
          <operation_timeout_ms>10000</operation_timeout_ms>
          <session_timeout_ms>30000</session_timeout_ms>
          <raft_logs_level>trace</raft_logs_level>
          <rotate_log_storage_interval>10000</rotate_log_storage_interval>
        </coordination_settings>        
        <raft_configuration>
          <server>
            <id>0</id>
            <hostname>Keeper-0</hostname>
            <port>9444</port>
          </server>
          <server>
            <id>1</id>
            <hostname>Keeper-1</hostname>
            <port>9444</port>
            <can_become_leader>true</can_become_leader>
          </server>
          <server>
            <id>2</id>
            <hostname>Keeper-2</hostname>
            <port>9444</port>
            <can_become_leader>true</can_become_leader>
          </server>
        </raft_configuration>
      </keeper_server>
    </clickhouse>    
