# Setup ClickHouse Keeper settings
apiVersion: v1
kind: ConfigMap
metadata:
  name: keeper-config
data:
  keeper_config.xml: |
    <clickhouse>
      <logger>
          <level>debug</level>
          <!--log>/var/lib/clickhouse-keeper/logs/clickhouse-keeper.log</log-->
          <!--errorlog>/var/lib/clickhouse-keeper/logs/clickhouse-keeper.err.log</errorlog-->
          <!--size>1000M</size-->
          <!--count>10</count-->
          <console>1</console>
      </logger>        
      <listen_host>::1</listen_host>
      <path>/var/lib/clickhouse-keeper/</path>
      <core_path>/var/lib/clickhouse-keeper/cores</core_path>        
      <keeper_server>
        <tcp_port>2181</tcp_port>
        <server_id>pod_nr</server_id>
        <!--log_storage_path>/var/lib/clickhouse-keeper/logs</log_storage_path-->
        <snapshot_storage_path>/var/lib/clickhouse-keeper/coordination/snapshots</snapshot_storage_path>    
        <coordination_settings>
          <operation_timeout_ms>10000</operation_timeout_ms>
          <session_timeout_ms>30000</session_timeout_ms>
          <raft_logs_level>debug</raft_logs_level>
          <rotate_log_storage_interval>10000</rotate_log_storage_interval>
        </coordination_settings>        
        <raft_configuration>
          <server>
            <id>1</id>
            <hostname>Keeper-0</hostname>
            <port>9444</port>
              <can_become_leader>true</can_become_leader>
          </server>
          <server>
            <id>2</id>
            <hostname>Keeper-1</hostname>
            <port>9444</port>
            <can_become_leader>true</can_become_leader>
          </server>
          <server>
            <id>3</id>
            <hostname>Keeper-2</hostname>
            <port>9444</port>
            <can_become_leader>true</can_become_leader>
          </server>
        </raft_configuration>
      </keeper_server>
    </clickhouse>    
  entrypoint.sh: |
    #!/bin/sh
    IFS=- read -r var1 var2 <<< $HOSTNAME | sed 's/pod_nr/'$var2'/g' /etc/clickhouse-keeper/keeper_config.template > /etc/clickhouse-keeper/keeper_config.xml 
    set +x
    set -eo pipefail
    shopt -s nullglob
    
    DO_CHOWN=1
    if [ "${CLICKHOUSE_DO_NOT_CHOWN:-0}" = "1" ]; then
      DO_CHOWN=0
    fi
    
    CLICKHOUSE_UID="${CLICKHOUSE_UID:-"$(id -u clickhouse)"}"
    CLICKHOUSE_GID="${CLICKHOUSE_GID:-"$(id -g clickhouse)"}"
    
    # support --user
    if [ "$(id -u)" = "0" ]; then
      USER=$CLICKHOUSE_UID
      GROUP=$CLICKHOUSE_GID
      if command -v gosu &> /dev/null; then
        gosu="gosu $USER:$GROUP"
      elif command -v su-exec &> /dev/null; then
        gosu="su-exec $USER:$GROUP"
      else
        echo "No gosu/su-exec detected!"
        exit 1
      fi
    else
      USER="$(id -u)"
      GROUP="$(id -g)"
      gosu=""
      DO_CHOWN=0
    fi
    
