apiVersion: v1
kind: Service
metadata:
  name: keeper
  labels:
    app: keeper
    tier: persistence
spec:
  type: ClusterIP
  ports:
    - port: 9234
      name: raft
      nodePort: 9234
    - port: 9181
      name: zookeeper
      nodePort: 9181
  selector:
    app: keeper
    tier: persistence
