apiVersion: v1
kind: Service
metadata:
  name: keeper
  labels:
    app: keeper
    tier: persistence
spec:
  type: ClusterIP
  ports:
    - port: 9234
      name: sync
    - port: 2181
      name: zookeeper
  selector:
    app: keeper
    tier: persistence
