# Setup ClickHouse Keeper settings
apiVersion: v1
kind: ConfigMap
metadata:
  name: keeper-config
data:
  keeper_config.xml: |
    <clickhouse>
      <listen_host>0.0.0.0</listen_host>
      <keeper_server>
        <tcp_port>9181</tcp_port>
        <server_id>${SERVER_ID}</server_id>
        <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
        <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>    
        <coordination_settings>
          <operation_timeout_ms>10000</operation_timeout_ms>
          <session_timeout_ms>30000</session_timeout_ms>
          <raft_logs_level>trace</raft_logs_level>
        </coordination_settings>        
        <raft_configuration>
          <server>
            <id>0</id>
            <hostname>Keeper-0</hostname>
            <port>9234</port>
          </server>
          <server>
            <id>1</id>
            <hostname>Keeper-1</hostname>
            <port>9234</port>
          </server>
          <server>
            <id>2</id>
            <hostname>Keeper-2</hostname>
            <port>9234</port>
          </server>
        </raft_configuration>
      </keeper_server>
    </clickhouse>    
