resources:
  - keeper-statefull.yaml
  - keeper-service.yaml
  - keeper-config.yaml
  # - ch-lb.yaml
  # sed -'s/<server_id>1<\/server_id>/<server_id>2<\/server_id>/g' /etc/clickhouse-keeper/keeper_config.xml | tee /etc/clickhouse-keeper/keeper_config.xml2
  # echo "ruok" | nc localhost 9181 ; echo
