apiVersion: batch/v1
kind: Job
metadata:
  name: kubernetes-job-example
  labels:
    jobgroup: jobexample
spec:
  template:
    metadata:
      name: kubejob
      labels:
        jobgroup: jobexample
    spec:
      containers:
      - name: c
        image: quicklookup/ctxpipe:9616a9b
        args: ["100"]
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerlock
