apiVersion: batch/v1
kind: Job
metadata:
  name: syn-bytewax
  namespace: ingress
  labels:
    job-group: bytewax
spec:
  template:
    metadata:
      name: bytewaxjob
    spec:
      containers:
      - name: syn-bytewax
        image: quicklookup/ctxpipe:9616a9b
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-postgresql-ha-pgpool
              key: password
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clickhouse
              key: admin-password
        - name: SYN_IS_SNOWFLAKE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: snowflake
              key: SYN_IS_SNOWFLAKE_PASSWORD
      imagePullSecrets:
        - name: dockerlock
