apiVersion: v1
kind: Pod
metadata:
  name: syn2ch
spec:
  containers:
  - name: syn2ch
    image: quicklookup/ctxpipe:9616a9b
    env:
      - name: RECOVERY_DIR
        value: '/pipedrive/syn2ch'
      - name: RECOVERY_INIT
        value: 'python -m bytewax.recovery /pipedrive/syn2ch/ 2'
      - name: DB_PATH
        value: '/pipedrive/databases'
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgresql-postgresql-ha-pgpool
            key: password
      - name: CLICKHOUSE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: clickhouse
            key: admin-password
      - name: SYN_IS_SNOWFLAKE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: snowflake
            key: SYN_IS_SNOWFLAKE_PASSWORD
    volumeMounts:
      - mountPath: /pipedrive
        name: is-syn-segment-disc
  volumes:
    - name: is-syn-segment-disc
      persistentVolumeClaim:
        claimName: is-syn-segment-in-pvc
  imagePullSecrets:
    - name: dockerlock
