apiVersion: apps/v1
kind: Deployment
metadata:
  name: kadeck
spec:
  selector:
    matchLabels:
      app: kadeck
      tier: api
  replicas: 1
  template:
    metadata:
      labels:
        app: kadeck
        tier: api
    spec:
      containers:
      - name: kadeck
        image: xeotek/kadeck:5.1.3
        ports:
        - containerPort: 80
          name: http
        envFrom:
          - configMapRef:
              name: kadeck-config
