apiVersion: v1
kind: Service
metadata:
  name: kadeck
  labels:
    app: kadeck
    tier: api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
  selector:
    app: kadeck
    tier: api
