apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kadeck
spec:
  rules:
    - host: kadeck.contextsuite.com
      http:
        paths:
          - backend:
              service:
                name: kadeck
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - kadeck.contextsuite.com
      secretName: star-contextsuite-com
