apiVersion: apps/v1
kind: Deployment
metadata:
  name: kadeck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kadeck
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kadeck
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox:1.36
          command: ["sh", "-c", "chown 1000:1000 /data"]
          volumeMounts:
            - name: n8n-claim
              mountPath: /data
      containers:
        - env:
            - name: xeotek_kadeck_free
              value: stefan@snjallgogn.is
          image: xeotek/kadeck:5.1.3
          name: kadeck
          ports:
            - containerPort: 80
      restartPolicy: Always
