apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: db-pvc
  name: db-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi