apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: postgres
  name: postgresql-ha-postgresql-0
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 64Gi