apiVersion: v1
kind: Pod
metadata:
  labels:
    role: data
  name: postgresql
  namespace: default
spec:
  containers:
  - name: postgres
    image: postgres:11.7-alpine
    volumeMounts:
      - mountPath: /var/lib/postgresql/data
        name: postgresql-pvc

  volumes:
    - name: postgresql-pvc
      persistentVolumeClaim:
        claimName: postgresql-pvc