apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-chat
spec:
  selector:
    matchLabels:
      app: gpt-chat
      tier: web
  template:
    metadata:
      labels:
        app: gpt-chat
        tier: web
    spec:
      containers:
        - name: node
          image: quicklookup/gpt-chat:1a7b72b
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              port: 3000
              path: /api/status/alive
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 3000
              path: /api/status/ready
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
          envFrom:
            - configMapRef:
                name: gpt-chat-config
      imagePullSecrets:
        - name: dockerlock
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gpt-chat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node
  maxReplicas: 4
  minReplicas: 2
  targetCPUUtilizationPercentage: 60