apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctx
spec:
  selector:
    matchLabels:
      app: ctx
      tier: api
  template:
    metadata:
      labels:
        app: ctx
        tier: api
    spec:
      containers:
        - name: node
          image: quicklookup/ctx:1.0.0
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 8088
          livenessProbe:
            httpGet:
              port: 8088
              path: /api/status/alive
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8088
              path: /api/status/ready
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-postgresql-ha-pgpool
                key: password
          - name: NEO4J_PASSWORD
            valueFrom:
              secretKeyRef:
                name: contextsuite
                key: NEO4J_AUTH
          - name: CLICKHOUSE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: clickhouse
                key: admin-password
          - name: SOLR_PASSWORD
            valueFrom:
              secretKeyRef:
                name: solr
                key: solr-password
          envFrom:
            - configMapRef:
                name: ctx-config
      imagePullSecrets:
        - name: dockerlock

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ctx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ctx
  maxReplicas: 4
  minReplicas: 2
  targetCPUUtilizationPercentage: 60