apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground
spec:
  selector:
    matchLabels:
      app: playground
      tier: gui
  template:
    metadata:
      labels:
        app: playground
        tier: gui
    spec:
      containers:
        - name: node
          image: quicklookup/playground:74db38b
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          envFrom:
            - configMapRef:
                name: playground-config
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: playground
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: playground
  maxReplicas: 3
  minReplicas: 2
  targetCPUUtilizationPercentage: 60