apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress
spec:
  selector:
    matchLabels:
      app: ingress
      tier: api
  replicas: 1
  template:
    metadata:
      labels:
        app: ingress
        tier: api
    spec:
      containers:
      - name: ingress
        image: quicklookup/ingress:v1.0.38
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 2222
          name: sftp
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
            httpHeaders:
              - name: writekey
                value: xZN8!E6d4aXns2ty
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
            scheme: HTTP
            httpHeaders:
              - name: writekey
                value: xZN8!E6d4aXns2ty
          initialDelaySeconds: 7
          periodSeconds: 3
        restartPolicy: Never
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: POSTGRES_PASSWORD
          - name: NEO4J_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: NEO4J_PASSWORD
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: S3_ACCESS_KEY
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: S3_SECRET_KEY
        envFrom:
          - configMapRef:
              name: ingress-config
        volumeMounts:
          - mountPath: /tmp
            name: sftp
      imagePullSecrets:
        - name: dockerlock
      volumes:
        - hostPath:
            path: /data/sftp
          name: sftp

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ingress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ingress
  maxReplicas: 6
  minReplicas: 3
  targetCPUUtilizationPercentage: 60