apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-config
data:
  ## Kafka
  KAFKA_HOST: 'kafka.default:9092'
  KAFKA_PORT: '9092'

  ## Redis
  REDIS_HOST: 'redis-master.default'
  REDIS_PORT: '6379'
  REDIS_DB: '0'
  REDIS_LOCAL: 'true'

  ## Postgres
  POSTGRES_HOST: 'postgresql-postgresql-ha-postgresql-headless.default'
  POSTGRES_URI: 'jdbc:postgresql://postgresql-postgresql-ha-postgresql-headless.default:5432/ssp'
  POSTGRES_PORT: '5432'
  POSTGRES_DB: 'ssp'
  POSTGRES_USER: 'postgres'

  # Neo4j
  NEO4J_URI: 'neo4j://neo4j.default:7687'
  NEO4J_HOST: 'neo4j.default'
  NEO4J_USER: 'admin'
  NEO4J_DATABASE: 'contextsuite'

  S3_REGION: 'ams3'
  S3_ENDPOINT: 'https://cxs.ingression.ams3.digitaloceanspaces.com'

  SPRING_PROFILES_ACTIVE: 'prod'
