apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: ingress-pvc
  name: ingress-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi