apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctxin
spec:
  selector:
    matchLabels:
      app: ingress
      tier: api
  replicas: 1
  template:
    metadata:
      labels:
        app: ingress
        tier: api
    spec:
      containers:
      - name: ingress
        image: quicklookup/ingress:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8088
        livenessProbe:
          httpGet:
            port: 8088
            path: /api/status/alive
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            port: 8088
            path: /api/status/ready
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: POSTGRES_PASSWORD
          - name: NEO4J_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: NEO4J_PASSWORD
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: S3_ACCESS_KEY
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: S3_SECRET_KEY
        envFrom:
          - configMapRef:
              name: ingress-config

      imagePullSecrets:
        - name: dockerlock

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ingress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ingress
  maxReplicas: 6
  minReplicas: 1
  targetCPUUtilizationPercentage: 30