apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress
spec:
  selector:
    matchLabels:
      app: ingress
      tier: api
  replicas: 1
  template:
    metadata:
      labels:
        app: ingress
        tier: api
    spec:
      containers:
      - name: ingress
        image: quicklookup/ingress:v1.0.23
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 2222
          name: sftp
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: POSTGRES_PASSWORD
          - name: NEO4J_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: NEO4J_PASSWORD
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: S3_ACCESS_KEY
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: ingress-secrets
                key: S3_SECRET_KEY
        envFrom:
          - configMapRef:
              name: ingress-config
        volumeMounts:
            - mountPath: /tmp
              name: ingress-pvc
      volumes:
        - name: ingress-pvc
          persistentVolumeClaim:
            claimName: ingress-pvc
      imagePullSecrets:
        - name: dockerlock

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ingress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ingress
  maxReplicas: 1
  minReplicas: 1
  targetCPUUtilizationPercentage: 60