apiVersion: v1
kind: Pod
metadata:
  name: nova2ch
spec:
  containers:
  - name: nova2ch
    image: quicklookup/qlingress:1.0.6
    env:
      - name: CLICKHOUSE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: clickhouse
            key: admin-password
    volumeMounts:
      - mountPath: /pipedrive
        name: pipedrive
    securityContext:
      readOnlyRootFilesystem: false
      runAsUser: 0
      capabilities:
        add:
          - NET_ADMIN
  dnsPolicy: ClusterFirst
  volumes:
    - hostPath:
        path: /data/pipedrive
      name: pipedrive
  imagePullSecrets:
    - name: dockerlock
