apiVersion: v1
kind: ConfigMap
metadata:
  name: syn-is-config
data:
  TABLE: 'cst.semantic_events_new'
  WRITE_KEY: 'xZN8!E6d4aXns2ty'
  RECOVERY_DIR: '/pipedrive/syn2ch'
  RECOVERY_INIT: 'python -m bytewax.recovery /pipedrive/syn2ch/ 2'
  SYN_IS_SNOWFLAKE_ACCOUNT: 'rg83886.eu-west-1'
  SYN_IS_SNOWFLAKE_USER: 'stefan'

  bytewax.run.sh: |
    #!/bin/sh
    python -m bytewax.run -p1 'pipelines/flows/json_kafka_ingress:get_flow("xZN8!E6d4aXns2ty", batch_size=10000, kafka_batch_size=5000, kafka_topics=["se2-syn-is"], timeout=15, table="cst.semantic_events_new", from_date="2024-01-14 20:10:00")'

  CLICKHOUSE_HOST: 'cxss3.default'
  CLICKHOUSE_PORT: '8123'
  CLICKHOUSE_DB: 'cst'
  CLICKHOUSE_USER: 'cxs'

  KAFKA_HOST: 'kafka.default'
  KAFKA_PORT: '9092'

  REDIS_HOST: 'redis-master.default'
  REDIS_PORT: '6379'
  REDIS_DB: '0'
  REDIS_LOCAL: 'true'

  POSTGRES_PORT: '5432'
  POSTGRES_DB: 'ssp'
  POSTGRES_USER: 'postgres'
  POSTGRES_HOST: 'postgresql-postgresql-ha-postgresql-headless.default'

  DB_PATH: '/pipedrive/databases'
  RAW_PATH: '/pipedrive/raw'
  KEEP_CONTAINER_ALIVE: "false"