apiVersion: batch/v1
kind: Job
metadata:
  name: syn-se-2-ch
  labels:
    jobgroup: pipeline
spec:
  template:
    metadata:
      name: kubejob
      labels:
        jobgroup: pipeline
    spec:
      containers:
      - name: ctxpipe-syn-se-2-ch
        image: quicklookup/ctxpipe:1e20627
        command:
          - /bin/sh
        env:
          - name: TIMEOUT
            value: "60"
          - name: KAFKA_BATCH_SIZE
            value: "5000"
          - name: BATCH_SIZE
            value: "10000"
          - name: SNAPSHOT_INTERVAL
            value: "8640"
          - name: TABLE
            value: semantic.sem_events
          - name: RECOVERY_INIT
            value: python -m bytewax.recovery /pipedrive/syn2ch/ 2
          - name: DB_PATH
            value: /pipedrive/db
          - name: RECOVERY_DIR
            value: '/pipedrive/syn2ch'
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-postgresql-ha-pgpool
                key: password
          - name: CLICKHOUSE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: clickhouse
                key: admin-password
          - name: SYN_IS_SNOWFLAKE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: snowflake
                key: SYN_IS_SNOWFLAKE_PASSWORD
        volumeMounts:
          - mountPath: /pipedrive
            name: pipedrive
      volumes:
      - hostPath:
          path: /data/pipedrive
        name: pipedrive
      imagePullSecrets:
        - name: dockerlock
      restartPolicy: Never
