apiVersion: v1
kind: Pod
metadata:
  annotations:
    field.cattle.io/description: stores semantic events Sýn
  labels:
    job-name: syn2ch-pipeline
  name: syn2ch-pipeline
  namespace: ingress
spec:
  selector:
    matchLabels:
      job-name: syn2ch-pipeline
  template:
    metadata:
      labels:
        job-name: syn2ch-pipeline
    spec:
      containers:
      - command:
        - /bin/sh
        env:
        - name: TIMEOUT
          value: "60"
        - name: KAFKA_BATCH_SIZE
          value: "5000"
        - name: BATCH_SIZE
          value: "10000"
        - name: SNAPSHOT_INTERVAL
          value: "8640"
        - name: TABLE
          value: semantic.sem_events
        - name: RECOVERY_DIR
          value: /pipedrive/syn2ch
        - name: RECOVERY_INIT
          value: python -m bytewax.recovery /pipedrive/syn2ch/ 2
        - name: DB_PATH
          value: /pipedrive/databases
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin-password
              name: clickhouse
              optional: false
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgresql-postgresql-ha-pgpool
              optional: false
        - name: WRITE_KEY
          valueFrom:
            secretKeyRef:
              key: SYN_IS_WRITE_KEY
              name: customer
              optional: false
        - name: SYN_IS_SNOWFLAKE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SYN_IS_SNOWFLAKE_PASSWORD
              name: customer
              optional: false
        envFrom:
        - configMapRef:
            name: ctxpipe-config
        image: quicklookup/ctxpipe:9616a9b
        imagePullPolicy: IfNotPresent
        name: syn2ch-pipeline
        volumeMounts:
        - mountPath: /pipedrive
          name: pipedrive
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerlock
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data/pipedrive
        name: pipedrive


apiVersion: v1
kind: Pod
metadata:
  name: syn2ch
spec:
  containers:
  - name: syn2ch
    image: quicklookup/ctxpipe:9616a9b
    env:
      - name: TIMEOUT
        value: "60"
      - name: KAFKA_BATCH_SIZE
        value: "5000"
      - name: BATCH_SIZE
        value: "10000"
      - name: SNAPSHOT_INTERVAL
        value: "8640"
      - name: TABLE
        value: semantic.sem_events
      - name: RECOVERY_INIT
        value: python -m bytewax.recovery /pipedrive/syn2ch/ 2
      - name: DB_PATH
        value: /pipedrive/databases
      - name: RECOVERY_DIR
        value: '/pipedrive/syn2ch'
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgresql-postgresql-ha-pgpool
            key: password
      - name: CLICKHOUSE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: clickhouse
            key: admin-password
      - name: SYN_IS_SNOWFLAKE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: snowflake
            key: SYN_IS_SNOWFLAKE_PASSWORD
    volumeMounts:
      - mountPath: /pipedrive
        name: pipedrive
  volumes:
  - hostPath:
      path: /data/pipedrive
    name: pipedrive
  imagePullSecrets:
    - name: dockerlock
