apiVersion: v1
kind: Pod
metadata:
  name: syn2ch-pipe
spec:
  containers:
  - name: syn2ch-pipe
    image: quicklookup/ctxpipe:a4cd9a6
    envFrom:
      - configMapRef:
          name: syn-is-config
    env:
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgresql-postgresql-ha-pgpool
            key: password
      - name: CLICKHOUSE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: clickhouse
            key: cxss3-password
      - name: SYN_IS_SNOWFLAKE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: snowflake
            key: SYN_IS_SNOWFLAKE_PASSWORD
    volumeMounts:
      - mountPath: /pipedrive
        name: pipedrive
      - mountPath: /pipelines/bytewax.run.sh
        name: config-volume
        subPath: bytewax.run.sh
    imagePullPolicy: Always
    restartPolicy: Always
  volumes:
  - name: config-volume
    configMap:
      name: syn-is-config
      defaultMode: 0555
  - hostPath:
      path: /data/pipedrive
    name: pipedrive
  imagePullSecrets:
    - name: dockerlock
