apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: contexsuite-cdn-rwm-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
