apiVersion: v1
kind: PersistentVolume
metadata:
  name: contextsuite-pv
spec:
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce