apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: contexsuite-cdn-claim
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
