apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["192.168.50.125","192.168.50.159","192.168.50.66"],"port":443,"protocol":"HTTPS","serviceName":"solutions:contextsuite","ingressName":"solutions:contextsuite","hostname":"app.contextsuite.com","path":"/","allNodes":false}]
  name: contextsuite
spec:
  defaultBackend:
    service:
      name: contextsuite
      port:
        number: 3000
  rules:
    - host: app.contextsuite.com
      http:
        paths:
          - backend:
              service:
                name: contextsuite
                port:
                  number: 3000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - app.contextsuite.com
      secretName: wild-contextsuite-com-cert
